const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createHistory}=require('../electron/session-history.cjs');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'lishon-session-'));let time=0;const history=createHistory({now:()=>time});history.configure(root,true);return {root,history,at:n=>time=n};}
const item={text:'The meeting starts tomorrow.',translations:[{target:'zh',translation:'会议明天开始。'},{target:'ja',translation:'会議は明日始まります。'}]};
test('only sessions over 15 active seconds are saved, including a single earlier caption',()=>{const f=fixture(),h=f.history;h.begin('screen');h.add('screen',item);f.at(15000);h.tick();assert.equal(h.list().items.length,0);f.at(15001);h.tick();assert.equal(h.list().items.length,1);const file=h.resolve(h.list().items[0].id);assert.match(fs.readFileSync(file,'utf8'),/会议明天开始/);assert.match(fs.readFileSync(file,'utf8'),/会議/);h.end('screen');h.begin('audio');h.add('audio',item);f.at(16000);h.end('audio');assert.equal(h.list().items.length,1);});
test('pauses do not count toward duration and resuming preserves the same file',()=>{const f=fixture(),h=f.history;h.begin('screen');h.add('screen',item);f.at(10000);h.pause('screen',true);f.at(60000);h.tick();assert.equal(h.list().items.length,0);h.pause('screen',false);f.at(66000);h.tick();const row=h.list().items[0];h.add('screen',{...item,text:'Second sentence'});assert.equal(h.list().items[0].id,row.id);assert.match(fs.readFileSync(h.resolve(row.id),'utf8'),/Second sentence/);});
test('disable, restart, rename and bulk deletion preserve unrelated files and monotonic names',()=>{const f=fixture(),h=f.history;for(const origin of ['screen','audio']){h.begin(origin);h.add(origin,item);}f.at(16000);h.tick();const rows=h.list().items;assert.equal(rows.length,2);h.configure(f.root,false);assert.equal(h.list().items.length,2);const reopened=createHistory();reopened.configure(f.root,false);reopened.rename(rows[0].id,'Project $1 / notes');assert.equal(reopened.read(rows[0].id).name,'Project $1 / notes');const other=path.join(f.root,'personal.md');fs.writeFileSync(other,'keep');const files=rows.map(r=>reopened.resolve(r.id));reopened.remove(rows.map(r=>r.id));assert.ok(files.every(f=>!fs.existsSync(f)));assert.equal(fs.readFileSync(other,'utf8'),'keep');assert.equal(JSON.parse(fs.readFileSync(path.join(f.root,'.lishon-history.json'))).next,3);});
test('forged history filenames cannot open or delete files outside storage',()=>{const f=fixture();const outside=path.join(path.dirname(f.root),'unrelated-'+Date.now()+'.txt');fs.writeFileSync(outside,'keep');fs.writeFileSync(path.join(f.root,'.lishon-history.json'),JSON.stringify({version:1,next:2,items:[{id:'x',file:'../'+path.basename(outside)}]}));assert.throws(()=>createHistory().configure(f.root,true),/Invalid history filename/);assert.equal(fs.readFileSync(outside,'utf8'),'keep');});
test('earlier Markdown history opens with its original and every target language',()=>{const f=fixture();fs.writeFileSync(path.join(f.root,'lishon-abcdef.md'),'# Old meeting\n\n**12:00:00**\n\nHello team.\n\nzh: 大家好。\n\nfr: Bonjour à tous.\n\n---\n\n**12:00:05**\n\nGoodbye.\n\nzh: 再见。');fs.writeFileSync(path.join(f.root,'.lishon-history.json'),JSON.stringify({version:1,next:2,items:[{id:'old',file:'lishon-abcdef.md',name:'Old meeting'}]}));const h=createHistory();h.configure(f.root,false);const doc=h.read('old');assert.equal(doc.entries.length,2);assert.equal(doc.entries[0].text,'Hello team.');assert.deepEqual(doc.entries[0].translations,[{target:'zh',translation:'大家好。'},{target:'fr',translation:'Bonjour à tous.'}]);h.rename('old','Renamed meeting');assert.equal(h.read('old').name,'Renamed meeting');assert.equal(h.read('old').entries[1].translations[0].translation,'再见。');});
