import React,{useEffect,useState} from 'react';
import {Rows3,Languages,Maximize2,Minimize2,Download,X,ListOrdered} from 'lucide-react';
import {api} from './bridge';
import {t,localeTag,setLocale} from './i18n';
import {historyGroups} from '../shared/history-document.mjs';
export default function HistoryReader(){
 const [doc,setDoc]=useState(null),[mode,setMode]=useState('paired'),[full,setFull]=useState(false),[exports,setExports]=useState(false),[busy,setBusy]=useState(false),[showLabels,setShowLabels]=useState(true),[error,setError]=useState('');
 function applySettings(s){document.documentElement.dataset.theme=s.theme;setLocale(s.uiLanguage);}
 async function load(){try{const value=await api.call('history-reader',{action:'read'});applySettings(value.settings);setDoc(value.document);setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{load();const off=[api.on('settings',applySettings),api.on('history-reader-state',s=>setFull(s.fullscreen)),api.on('history-changed',load)];return()=>off.forEach(fn=>fn());},[]);
 const label=code=>{if(!code||code==='auto')return t('识别语言');try{return new Intl.DisplayNames([localeTag()],{type:'language'}).of(code);}catch{return code;}};
 async function action(action){try{await api.call('history-reader',{action});}catch(e){setError(e.message);}}
 async function exportFile(format){setExports(false);setBusy(true);try{await api.call('history-reader',{action:'export',format,mode,showLabels});setError('');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className={'history-reader-shell '+(full?'fullscreen':'')}><header className="reader-toolbar"><span>{t('历史记录阅读')}</span><div><button aria-label={t('切换阅读方式')} title={mode==='paired'?t('按语种归类'):t('逐条对照')} aria-pressed={mode==='grouped'} onClick={()=>setMode(mode==='paired'?'grouped':'paired')}>{mode==='paired'?<Languages size={18}/>:<Rows3 size={18}/>}</button><button aria-label={t('显示序号和语种')} title={t('显示序号和语种')} aria-pressed={showLabels} onClick={()=>setShowLabels(!showLabels)}><ListOrdered size={18}/></button><div className="reader-export"><button aria-label={t('导出文档')} title={t('导出文档')} disabled={!doc||busy} aria-expanded={exports} onClick={()=>setExports(!exports)}><Download size={18}/></button>{exports&&<div className="reader-export-menu"><button onClick={()=>exportFile('md')}>Markdown</button><button onClick={()=>exportFile('pdf')}>PDF</button></div>}</div><button aria-label={full?t('退出全屏'):t('全屏阅读')} title={full?t('退出全屏'):t('全屏阅读')} onClick={()=>action('fullscreen')}>{full?<Minimize2 size={18}/>:<Maximize2 size={18}/>}</button><button aria-label={t('关闭阅读面板')} title={t('关闭阅读面板')} onClick={()=>action('close')}><X size={18}/></button></div></header><main className="reader-scroll">{error&&<div className="error-banner" role="alert">{error}</div>}{doc&&<article className="reader-document"><h1>{doc.name}</h1><p className="reader-meta">{new Date(doc.created).toLocaleString(localeTag())} · {mode==='paired'?t('逐条对照'):t('按语种归类')}</p>{mode==='paired'?doc.entries.map((entry,i)=><section className="reader-entry" key={i}>{showLabels&&<div className="reader-sequence">{i+1}</div>}<div className="reader-original">{showLabels&&<h2>{label(entry.source)}</h2>}<p>{entry.text}</p></div>{entry.translations.map((row,j)=><div className="reader-translation" key={j}>{showLabels&&<h2>{label(row.target)}</h2>}<p>{row.translation}</p></div>)}</section>):historyGroups(doc.entries).map((group,i)=><section className="reader-language-group" key={i}>{showLabels&&<h2>{label(group.code)}{group.original&&<small>{t('原文')}</small>}</h2>}{group.texts.map((text,j)=><p key={j}>{showLabels&&<span className="reader-inline-sequence">{group.numbers[j]} · </span>}{text}</p>)}</section>)}</article>}</main></div>;
}
