import React,{useEffect,useState} from 'react';
import {FolderOpen,Trash2,History as HistoryIcon} from 'lucide-react';
import {api} from './bridge';
import {t} from './i18n';
export function HistoryStorage({settings,update}){
 const [error,setError]=useState('');
 async function choose(enable=false){try{setError('');const result=await api.call('history-folder',{enable});if(result)await update({historyEnabled:result.enabled,historyDirectory:result.directory});}catch(e){setError(e.message);}}
 return <div className="history-storage"><p>{t('连续屏幕字幕或实时听译超过 15 秒后自动保存。关闭功能不会删除已有记录。')}</p><div className="storage-row"><FolderOpen size={18}/><div><strong>{t('历史记录存储位置')}</strong><p title={settings.historyDirectory}>{settings.historyDirectory||t('请先选择存储文件夹')}</p></div><button onClick={()=>choose(!settings.historyEnabled)}>{t('选择文件夹')}</button>{settings.historyDirectory&&<button onClick={()=>api.call('session-history',{action:'folder'}).catch(e=>setError(e.message))}>{t('打开文件夹')}</button>}</div>{error&&<p role="alert">{error}</p>}</div>;
}
export default function SessionHistory({settings,update}){
 const [data,setData]=useState({items:[]}),[selected,setSelected]=useState([]),[editing,setEditing]=useState(null),[title,setTitle]=useState(''),[error,setError]=useState('');
 async function call(args={}){try{const r=await api.call('session-history',args);if(r?.items)setData(r);setError('');return r;}catch(e){setError(e.message);}}
 useEffect(()=>{call();return api.on('history-changed',()=>call());},[settings.historyDirectory,settings.historyEnabled]);
 async function remove(ids){await call({action:'delete',ids});setSelected([]);}
 async function rename(){if(!editing)return;const id=editing;setEditing(null);await call({action:'rename',id,name:title});}
 return <div className="session-history">{!settings.historyEnabled&&<div className="history-setup"><HistoryIcon size={23}/><p>{t('开启本地历史记录，先设置保存位置。超过 15 秒的字幕与听译会话将自动记录。')}</p>{settings.historyDirectory&&<button onClick={()=>update({historyEnabled:true})}>{t('开启历史记录')}</button>}</div>}<HistoryStorage settings={settings} update={update}/><div className="history-toolbar"><label><input type="checkbox" aria-label={t('选择本页记录')} checked={data.items.length>0&&selected.length===data.items.length} onChange={e=>setSelected(e.target.checked?data.items.map(x=>x.id):[])}/>{t('选择本页')}</label><span>{t('双击名称重命名，双击内容打开阅读面板。')}</span><button disabled={!selected.length} onClick={()=>remove(selected)}><Trash2 size={16}/>{t('批量删除 ')}{selected.length||''}</button></div>{error&&<p role="alert" className="error-banner">{error}</p>}<div className="session-history-list">{data.items.map(row=><article key={row.id}><input type="checkbox" aria-label={t('选择 ')+row.name} checked={selected.includes(row.id)} onChange={e=>setSelected(e.target.checked?[...selected,row.id]:selected.filter(x=>x!==row.id))}/>{editing===row.id?<input className="history-name-input" autoFocus maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} onBlur={rename} onKeyDown={e=>{if(e.key==='Enter')rename();if(e.key==='Escape')setEditing(null);}}/>:<button className="history-name" title={row.name} onDoubleClick={()=>{setEditing(row.id);setTitle(row.name);}}>{row.name}</button>}<button className="history-preview" title={row.preview} onDoubleClick={()=>call({action:'open',id:row.id})}>{row.preview}</button><button className="icon-button" aria-label={t('打开文件夹')} onClick={()=>call({action:'reveal',id:row.id})}><FolderOpen size={17}/></button><button className="icon-button" aria-label={t('删除记录')} onClick={()=>remove([row.id])}><Trash2 size={17}/></button></article>)}{!data.items.length&&<p className="library-empty">{t('还没有翻译历史记录')}</p>}</div></div>;
}
